<?php

namespace Database\Seeders;

use App\Models\Recipe;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    public function run(): void
    {
        $recipes = [
            [
                'name' => 'Adobong Manok',
                'description' => 'Classic Filipino chicken adobo braised in soy sauce, vinegar, and garlic.',
                'instructions' => "1. Combine chicken, soy sauce, vinegar, garlic, and peppercorns in a pot. Marinate 15 minutes.\n2. Bring to a boil, then simmer covered for 25 minutes.\n3. Uncover, add bay leaves, and simmer until sauce reduces and thickens.\n4. Optional: pan-fry chicken pieces for extra color before serving.",
                'cooking_tips' => 'Do not stir too much vinegar in too early — let it boil uncovered first to mellow the sharpness.',
                'region' => 'Luzon',
                'prep_time' => 10,
                'cook_time' => 40,
                'servings' => 4,
                'meal_type' => 'lunch',
                'difficulty' => 'easy',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/3/38/Chicken_adobo.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Chicken_adobo.jpg',
                'image_attribution' => 'Chicken adobo — dbgg1979 on Flickr (CC BY 2.0), via Wikimedia Commons',
                'calories' => 320, 'protein' => 28, 'carbs' => 6, 'fat' => 20,
                'ingredients' => [
                    ['name' => 'chicken thighs', 'quantity' => '1', 'unit' => 'kg'],
                    ['name' => 'soy sauce', 'quantity' => '1/2', 'unit' => 'cup'],
                    ['name' => 'white vinegar', 'quantity' => '1/3', 'unit' => 'cup'],
                    ['name' => 'garlic', 'quantity' => '6', 'unit' => 'cloves'],
                    ['name' => 'bay leaves', 'quantity' => '3', 'unit' => 'pcs'],
                    ['name' => 'whole peppercorns', 'quantity' => '1', 'unit' => 'tsp'],
                ],
            ],
            [
                'name' => 'Sinigang na Baboy',
                'description' => 'Sour tamarind pork soup with vegetables.',
                'instructions' => "1. Boil pork in water until tender, skimming scum.\n2. Add tamarind mix or fresh tamarind, tomatoes, and onions.\n3. Add radish and eggplant, simmer 10 minutes.\n4. Add string beans and kangkong, simmer 3 more minutes.\n5. Season with fish sauce to taste.",
                'cooking_tips' => 'Add leafy greens like kangkong last so they do not overcook.',
                'region' => 'Luzon',
                'prep_time' => 15,
                'cook_time' => 50,
                'servings' => 6,
                'meal_type' => 'lunch',
                'difficulty' => 'medium',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Sinigang_na_Baboy_DSCF4234.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Sinigang_na_Baboy_DSCF4234.jpg',
                'image_attribution' => 'Sinigang na Baboy — Joy D. Ganaden (CC BY-SA 4.0), via Wikimedia Commons',
                'calories' => 280, 'protein' => 22, 'carbs' => 10, 'fat' => 16,
                'ingredients' => [
                    ['name' => 'pork belly', 'quantity' => '1', 'unit' => 'kg'],
                    ['name' => 'tamarind soup mix', 'quantity' => '1', 'unit' => 'pack'],
                    ['name' => 'radish', 'quantity' => '1', 'unit' => 'pc'],
                    ['name' => 'eggplant', 'quantity' => '2', 'unit' => 'pcs'],
                    ['name' => 'string beans', 'quantity' => '1', 'unit' => 'bundle'],
                    ['name' => 'kangkong', 'quantity' => '1', 'unit' => 'bundle'],
                    ['name' => 'tomatoes', 'quantity' => '2', 'unit' => 'pcs'],
                    ['name' => 'fish sauce', 'quantity' => '2', 'unit' => 'tbsp'],
                ],
            ],
            [
                'name' => 'Pancit Bihon',
                'description' => 'Stir-fried rice noodles with vegetables and chicken.',
                'instructions' => "1. Soak bihon noodles in water until soft.\n2. Saute garlic and onion, add chicken and cook through.\n3. Add carrots and cabbage, stir-fry briefly.\n4. Pour in broth and soy sauce, add noodles, toss until liquid is absorbed.\n5. Garnish with calamansi and spring onions.",
                'cooking_tips' => 'Do not oversoak the noodles — they will finish cooking in the broth.',
                'region' => 'Luzon',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 5,
                'meal_type' => 'dinner',
                'difficulty' => 'easy',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/4/41/Pancit_bihon_1.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Pancit_bihon_1.jpg',
                'image_attribution' => 'Pancit bihon — Obsidian Soul (CC0), via Wikimedia Commons',
                'calories' => 300, 'protein' => 15, 'carbs' => 45, 'fat' => 8,
                'ingredients' => [
                    ['name' => 'bihon noodles', 'quantity' => '250', 'unit' => 'g'],
                    ['name' => 'chicken breast', 'quantity' => '300', 'unit' => 'g'],
                    ['name' => 'carrots', 'quantity' => '1', 'unit' => 'pc'],
                    ['name' => 'cabbage', 'quantity' => '1/2', 'unit' => 'head'],
                    ['name' => 'soy sauce', 'quantity' => '3', 'unit' => 'tbsp'],
                    ['name' => 'chicken broth', 'quantity' => '2', 'unit' => 'cup'],
                    ['name' => 'calamansi', 'quantity' => '4', 'unit' => 'pcs'],
                ],
            ],
            [
                'name' => 'Tinolang Manok',
                'description' => 'Ginger chicken soup with green papaya and chili leaves.',
                'instructions' => "1. Saute ginger, garlic, and onion until fragrant.\n2. Add chicken pieces, cook until lightly browned.\n3. Pour in fish sauce and water, simmer 20 minutes.\n4. Add green papaya, simmer until tender.\n5. Add chili leaves or spinach just before serving.",
                'cooking_tips' => 'Use plenty of ginger — it is the backbone flavor of this dish.',
                'region' => 'Visayas',
                'prep_time' => 10,
                'cook_time' => 35,
                'servings' => 4,
                'meal_type' => 'lunch',
                'difficulty' => 'easy',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/5/56/Chicken_tinola_with_green_papaya_and_lemongrass.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Chicken_tinola_with_green_papaya_and_lemongrass.jpg',
                'image_attribution' => 'Chicken tinola — Obsidian Soul (CC0), via Wikimedia Commons',
                'calories' => 250, 'protein' => 26, 'carbs' => 8, 'fat' => 12,
                'ingredients' => [
                    ['name' => 'chicken', 'quantity' => '1', 'unit' => 'kg'],
                    ['name' => 'ginger', 'quantity' => '2', 'unit' => 'thumbs'],
                    ['name' => 'green papaya', 'quantity' => '1', 'unit' => 'pc'],
                    ['name' => 'chili leaves', 'quantity' => '1', 'unit' => 'cup'],
                    ['name' => 'fish sauce', 'quantity' => '2', 'unit' => 'tbsp'],
                    ['name' => 'garlic', 'quantity' => '4', 'unit' => 'cloves'],
                    ['name' => 'onion', 'quantity' => '1', 'unit' => 'pc'],
                ],
            ],
            [
                'name' => 'Bicol Express',
                'description' => 'Spicy pork stew simmered in coconut milk and chilies.',
                'instructions' => "1. Saute garlic, onion, and ginger.\n2. Add pork, cook until lightly browned.\n3. Pour in coconut milk, simmer until pork is tender.\n4. Add shrimp paste and chilies, simmer until sauce thickens.",
                'cooking_tips' => 'Simmer the coconut milk slowly to prevent it from curdling.',
                'region' => 'Bicol',
                'prep_time' => 15,
                'cook_time' => 45,
                'servings' => 5,
                'meal_type' => 'dinner',
                'difficulty' => 'medium',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Bicol_Express_at_La_Herencia_Comida.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Bicol_Express_at_La_Herencia_Comida.jpg',
                'image_attribution' => 'Bicol Express — Ymirazudis (CC BY-SA 4.0), via Wikimedia Commons',
                'calories' => 400, 'protein' => 20, 'carbs' => 7, 'fat' => 32,
                'ingredients' => [
                    ['name' => 'pork belly', 'quantity' => '500', 'unit' => 'g'],
                    ['name' => 'coconut milk', 'quantity' => '2', 'unit' => 'cup'],
                    ['name' => 'shrimp paste', 'quantity' => '2', 'unit' => 'tbsp'],
                    ['name' => 'siling labuyo', 'quantity' => '10', 'unit' => 'pcs'],
                    ['name' => 'ginger', 'quantity' => '1', 'unit' => 'thumb'],
                    ['name' => 'garlic', 'quantity' => '4', 'unit' => 'cloves'],
                ],
            ],
            [
                'name' => 'Kare-Kare',
                'description' => 'Oxtail and vegetable stew in a rich peanut sauce.',
                'instructions' => "1. Boil oxtail until very tender.\n2. Saute garlic and onion, add peanut butter and annatto water.\n3. Add oxtail and broth, simmer until sauce thickens.\n4. Add eggplant, string beans, and banana blossom, simmer until cooked.\n5. Serve with bagoong on the side.",
                'cooking_tips' => 'Toast the ground peanuts or rice first for a deeper, nuttier sauce.',
                'region' => 'Luzon',
                'prep_time' => 20,
                'cook_time' => 120,
                'servings' => 6,
                'meal_type' => 'dinner',
                'difficulty' => 'hard',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Kare-kare_at_La_Herencia_Comida.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Kare-kare_at_La_Herencia_Comida.jpg',
                'image_attribution' => 'Kare-kare — Ymirazudis (CC BY-SA 4.0), via Wikimedia Commons',
                'calories' => 450, 'protein' => 25, 'carbs' => 14, 'fat' => 30,
                'ingredients' => [
                    ['name' => 'oxtail', 'quantity' => '1', 'unit' => 'kg'],
                    ['name' => 'peanut butter', 'quantity' => '1', 'unit' => 'cup'],
                    ['name' => 'annatto powder', 'quantity' => '2', 'unit' => 'tbsp'],
                    ['name' => 'eggplant', 'quantity' => '2', 'unit' => 'pcs'],
                    ['name' => 'string beans', 'quantity' => '1', 'unit' => 'bundle'],
                    ['name' => 'banana blossom', 'quantity' => '1', 'unit' => 'pc'],
                    ['name' => 'bagoong', 'quantity' => '4', 'unit' => 'tbsp'],
                ],
            ],
            [
                'name' => 'Ginisang Monggo',
                'description' => 'Sauteed mung bean soup with pork and malunggay leaves.',
                'instructions' => "1. Boil mung beans until soft.\n2. Saute garlic, onion, and tomato, add pork, cook through.\n3. Add boiled mung beans and broth, simmer 15 minutes.\n4. Add malunggay leaves, season with fish sauce.",
                'cooking_tips' => 'Mash some of the beans while cooking for a thicker, creamier texture.',
                'region' => 'Luzon',
                'prep_time' => 10,
                'cook_time' => 40,
                'servings' => 5,
                'meal_type' => 'lunch',
                'difficulty' => 'easy',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Ginisang_munggo_with_fried_bangus.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Ginisang_munggo_with_fried_bangus.jpg',
                'image_attribution' => 'Ginisang munggo — Pandakekok9 (CC0), via Wikimedia Commons',
                'calories' => 260, 'protein' => 16, 'carbs' => 30, 'fat' => 8,
                'ingredients' => [
                    ['name' => 'mung beans', 'quantity' => '1', 'unit' => 'cup'],
                    ['name' => 'pork', 'quantity' => '200', 'unit' => 'g'],
                    ['name' => 'malunggay leaves', 'quantity' => '1', 'unit' => 'cup'],
                    ['name' => 'tomato', 'quantity' => '1', 'unit' => 'pc'],
                    ['name' => 'garlic', 'quantity' => '3', 'unit' => 'cloves'],
                    ['name' => 'fish sauce', 'quantity' => '1', 'unit' => 'tbsp'],
                ],
            ],
            [
                'name' => 'Chicken Tinola-style Arroz Caldo',
                'description' => 'Ginger rice porridge with chicken, a comforting breakfast or merienda dish.',
                'instructions' => "1. Saute ginger, garlic, and onion.\n2. Add chicken, cook until lightly browned.\n3. Add rice, toast briefly, then pour in broth.\n4. Simmer, stirring occasionally, until rice is porridge-like.\n5. Top with fried garlic, spring onions, and calamansi.",
                'cooking_tips' => 'Stir often near the end so the rice does not stick to the pot.',
                'region' => 'Luzon',
                'prep_time' => 10,
                'cook_time' => 45,
                'servings' => 5,
                'meal_type' => 'breakfast',
                'difficulty' => 'easy',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Arroz_Caldo%2C_Grape_Custard%2C_Fruits%2C_Virgin_Light.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Arroz_Caldo,_Grape_Custard,_Fruits,_Virgin_Light.jpg',
                'image_attribution' => 'Arroz caldo — George Parilla (CC BY 2.0), via Wikimedia Commons',
                'calories' => 310, 'protein' => 18, 'carbs' => 40, 'fat' => 9,
                'ingredients' => [
                    ['name' => 'chicken', 'quantity' => '500', 'unit' => 'g'],
                    ['name' => 'rice', 'quantity' => '1', 'unit' => 'cup'],
                    ['name' => 'ginger', 'quantity' => '2', 'unit' => 'thumbs'],
                    ['name' => 'garlic', 'quantity' => '5', 'unit' => 'cloves'],
                    ['name' => 'fish sauce', 'quantity' => '2', 'unit' => 'tbsp'],
                    ['name' => 'calamansi', 'quantity' => '3', 'unit' => 'pcs'],
                ],
            ],
            [
                'name' => 'Laing',
                'description' => 'Taro leaves simmered slowly in coconut milk with chili.',
                'instructions' => "1. Layer dried taro leaves in a pot with coconut milk.\n2. Add shrimp paste, ginger, and chilies.\n3. Simmer without stirring too much until oil separates from the coconut milk.\n4. Add pork or dried fish if desired, simmer until tender.",
                'cooking_tips' => 'Avoid stirring too early — this can make the taro leaves itch on the throat.',
                'region' => 'Bicol',
                'prep_time' => 10,
                'cook_time' => 60,
                'servings' => 5,
                'meal_type' => 'lunch',
                'difficulty' => 'medium',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/5/59/Laing%2C_Bicolano_dish.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Laing,_Bicolano_dish.jpg',
                'image_attribution' => 'Laing — Lokalpedia (CC BY-SA 4.0), via Wikimedia Commons',
                'calories' => 290, 'protein' => 8, 'carbs' => 12, 'fat' => 24,
                'ingredients' => [
                    ['name' => 'dried taro leaves', 'quantity' => '200', 'unit' => 'g'],
                    ['name' => 'coconut milk', 'quantity' => '2', 'unit' => 'cup'],
                    ['name' => 'shrimp paste', 'quantity' => '2', 'unit' => 'tbsp'],
                    ['name' => 'siling labuyo', 'quantity' => '5', 'unit' => 'pcs'],
                    ['name' => 'ginger', 'quantity' => '1', 'unit' => 'thumb'],
                ],
            ],
            [
                'name' => 'Chopsuey',
                'description' => 'Mixed vegetable stir-fry with pork or shrimp in oyster sauce.',
                'instructions' => "1. Saute garlic and onion, add pork or shrimp, cook through.\n2. Add carrots and cauliflower, stir-fry 2 minutes.\n3. Add cabbage, snow peas, and broth.\n4. Season with oyster sauce, simmer briefly, thicken with cornstarch slurry.",
                'cooking_tips' => 'Add cabbage last so vegetables stay crisp-tender, not soggy.',
                'region' => 'Luzon',
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 4,
                'meal_type' => 'dinner',
                'difficulty' => 'easy',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Chopsuey%2C_Jun_2024.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Chopsuey,_Jun_2024.jpg',
                'image_attribution' => 'Chopsuey — Ralff Nestor Nacor (CC BY-SA 4.0), via Wikimedia Commons',
                'calories' => 220, 'protein' => 14, 'carbs' => 16, 'fat' => 10,
                'ingredients' => [
                    ['name' => 'pork', 'quantity' => '200', 'unit' => 'g'],
                    ['name' => 'carrots', 'quantity' => '1', 'unit' => 'pc'],
                    ['name' => 'cauliflower', 'quantity' => '1', 'unit' => 'cup'],
                    ['name' => 'cabbage', 'quantity' => '1/2', 'unit' => 'head'],
                    ['name' => 'snow peas', 'quantity' => '1', 'unit' => 'cup'],
                    ['name' => 'oyster sauce', 'quantity' => '3', 'unit' => 'tbsp'],
                    ['name' => 'cornstarch', 'quantity' => '1', 'unit' => 'tbsp'],
                ],
            ],
            [
                'name' => 'Ginataang Kalabasa',
                'description' => 'Squash and string beans simmered in coconut milk, often with shrimp.',
                'instructions' => "1. Saute garlic, onion, and ginger.\n2. Add shrimp or pork, cook briefly.\n3. Add squash, simmer until nearly tender.\n4. Pour in coconut milk, add string beans, simmer until squash is soft.",
                'cooking_tips' => 'Cut the squash evenly so it cooks at the same rate.',
                'region' => 'Visayas',
                'prep_time' => 10,
                'cook_time' => 30,
                'servings' => 4,
                'meal_type' => 'lunch',
                'difficulty' => 'easy',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Ginataang_kalabasa_at_hipon_%28shrimp%2C_calabaza%2C_green_beans%2C_and_eggplant_in_coconut_milk%29_-_Philippines.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Ginataang_kalabasa_at_hipon_(shrimp,_calabaza,_green_beans,_and_eggplant_in_coconut_milk)_-_Philippines.jpg',
                'image_attribution' => 'Ginataang kalabasa at hipon — Yvette Tan (CC BY 2.0), via Wikimedia Commons',
                'calories' => 240, 'protein' => 10, 'carbs' => 18, 'fat' => 16,
                'ingredients' => [
                    ['name' => 'squash', 'quantity' => '500', 'unit' => 'g'],
                    ['name' => 'string beans', 'quantity' => '1', 'unit' => 'bundle'],
                    ['name' => 'coconut milk', 'quantity' => '1.5', 'unit' => 'cup'],
                    ['name' => 'shrimp', 'quantity' => '200', 'unit' => 'g'],
                    ['name' => 'garlic', 'quantity' => '3', 'unit' => 'cloves'],
                    ['name' => 'ginger', 'quantity' => '1', 'unit' => 'thumb'],
                ],
            ],
            [
                'name' => 'Beef Caldereta',
                'description' => 'Rich beef stew in tomato sauce with liver spread, potatoes, and bell peppers.',
                'instructions' => "1. Marinate beef briefly, then brown in oil.\n2. Saute garlic and onion, return beef to pot.\n3. Add tomato sauce and water, simmer until beef is tender.\n4. Add potatoes and carrots, simmer until soft.\n5. Stir in liver spread and bell peppers, simmer 5 more minutes.",
                'cooking_tips' => 'Simmer low and slow — tough beef cuts need time to become tender.',
                'region' => 'Luzon',
                'prep_time' => 20,
                'cook_time' => 90,
                'servings' => 6,
                'meal_type' => 'dinner',
                'difficulty' => 'medium',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/d/df/Beef_Caldereta_Special.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Beef_Caldereta_Special.jpg',
                'image_attribution' => 'Beef Caldereta — LadyPinayForever (CC0), via Wikimedia Commons',
                'calories' => 420, 'protein' => 30, 'carbs' => 15, 'fat' => 26,
                'ingredients' => [
                    ['name' => 'beef chunks', 'quantity' => '1', 'unit' => 'kg'],
                    ['name' => 'tomato sauce', 'quantity' => '2', 'unit' => 'cup'],
                    ['name' => 'potatoes', 'quantity' => '3', 'unit' => 'pcs'],
                    ['name' => 'carrots', 'quantity' => '2', 'unit' => 'pcs'],
                    ['name' => 'bell peppers', 'quantity' => '2', 'unit' => 'pcs'],
                    ['name' => 'liver spread', 'quantity' => '3', 'unit' => 'tbsp'],
                    ['name' => 'garlic', 'quantity' => '5', 'unit' => 'cloves'],
                ],
            ],
            [
                'name' => 'Chicken Inasal',
                'description' => 'Bacolod-style grilled chicken marinated with calamansi, lemongrass, and annatto.',
                'instructions' => "1. Combine chicken, calamansi juice, lemongrass, garlic, ginger, and salt. Marinate for at least 30 minutes.\n2. Mix annatto powder with oil for basting.\n3. Grill chicken over medium heat, turning and basting until cooked through.\n4. Serve with rice and calamansi.",
                'cooking_tips' => 'Keep the grill at medium heat so the annatto basting does not burn before the chicken cooks through.',
                'region' => 'Visayas',
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 4,
                'meal_type' => 'dinner',
                'difficulty' => 'medium',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Chicken_inasal_%28Philippines%29.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Chicken_inasal_(Philippines).jpg',
                'image_attribution' => 'Chicken inasal — Obsidian Soul (CC BY-SA 4.0), via Wikimedia Commons',
                'calories' => 330, 'protein' => 31, 'carbs' => 5, 'fat' => 20,
                'ingredients' => [
                    ['name' => 'chicken', 'quantity' => '1', 'unit' => 'kg'],
                    ['name' => 'calamansi', 'quantity' => '8', 'unit' => 'pcs'],
                    ['name' => 'lemongrass', 'quantity' => '2', 'unit' => 'stalks'],
                    ['name' => 'annatto powder', 'quantity' => '1', 'unit' => 'tbsp'],
                    ['name' => 'garlic', 'quantity' => '4', 'unit' => 'cloves'],
                    ['name' => 'ginger', 'quantity' => '1', 'unit' => 'thumb'],
                ],
            ],
            [
                'name' => 'Kinilaw na Isda',
                'description' => 'A bright Mindanao-style fish kinilaw cured with vinegar, calamansi, ginger, and chilies.',
                'instructions' => "1. Use very fresh fish and keep it chilled.\n2. Toss fish with vinegar for 5 minutes, then drain excess vinegar.\n3. Add calamansi juice, ginger, onion, cucumber, and chilies.\n4. Season with salt and serve immediately.",
                'cooking_tips' => 'Use sashimi-grade fish from a trusted source; acid changes texture but is not a substitute for safe handling.',
                'region' => 'Mindanao',
                'prep_time' => 20,
                'cook_time' => 0,
                'servings' => 4,
                'meal_type' => 'lunch',
                'difficulty' => 'medium',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Kinilaw_na_isda_%28Philippines%29.jpg',
                'image_source_url' => 'https://commons.wikimedia.org/wiki/File:Kinilaw_na_isda_(Philippines).jpg',
                'image_attribution' => 'Kinilaw na isda — Yvette Tan (CC BY 2.0), via Wikimedia Commons',
                'calories' => 180, 'protein' => 25, 'carbs' => 6, 'fat' => 5,
                'ingredients' => [
                    ['name' => 'fresh fish', 'quantity' => '500', 'unit' => 'g'],
                    ['name' => 'cane vinegar', 'quantity' => '1/3', 'unit' => 'cup'],
                    ['name' => 'calamansi', 'quantity' => '6', 'unit' => 'pcs'],
                    ['name' => 'ginger', 'quantity' => '1', 'unit' => 'thumb'],
                    ['name' => 'red onion', 'quantity' => '1', 'unit' => 'pc'],
                    ['name' => 'cucumber', 'quantity' => '1', 'unit' => 'pc'],
                    ['name' => 'siling labuyo', 'quantity' => '2', 'unit' => 'pcs'],
                ],
            ],
        ];

        foreach ($recipes as $recipe) {
            $ingredients = $recipe['ingredients'];
            unset($recipe['ingredients']);
            unset($recipe['image'], $recipe['image_source_url'], $recipe['image_attribution']);

            // This is intentionally an upsert, rather than firstOrCreate: the
            // array above is the reviewed catalogue and seeding must also apply
            // editorial corrections to an existing local database.
            $model = Recipe::updateOrCreate(['name' => $recipe['name']], $recipe);
            $model->ingredients()->delete();
            $model->ingredients()->createMany($ingredients);
        }
    }
}
